"""Fix foreign key names and add evolution

Revision ID: 02b336b64078
Revises: 5c1a314f4e79
Create Date: 2026-04-26 06:53:08.516183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b336b64078'
down_revision = '5c1a314f4e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logs')
    op.drop_table('daily_coach_tips')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('nexus_flows')
    with op.batch_alter_table('archetype_content', schema=None) as batch_op:
        batch_op.alter_column('element',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('tarot_arcane',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('platform')
        batch_op.drop_column('type')

    with op.batch_alter_table('nexus_nodes', schema=None) as batch_op:
        batch_op.drop_column('config_json')

    with op.batch_alter_table('session_archive', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_archive', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('nexus_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_json', sa.TEXT(), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('archetype_content', schema=None) as batch_op:
        batch_op.alter_column('tarot_arcane',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('element',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('nexus_flows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_trigger', sa.VARCHAR(length=50), nullable=True),
    sa.Column('flow_sequence', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pattern', sa.VARCHAR(length=100), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('personal_notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('daily_coach_tips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('archetype_id', sa.INTEGER(), nullable=True),
    sa.Column('day_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phys_content', sa.TEXT(), nullable=True),
    sa.Column('ment_content', sa.TEXT(), nullable=True),
    sa.Column('harm_content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetype_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
