"""sync all columns

Revision ID: 5c1a314f4e79
Revises: 
Create Date: 2026-03-28 13:56:27.842853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1a314f4e79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archetype_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shadow_side', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avoid_spheres', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('partner_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('financial_tip', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_potential', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('health_tips', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mission', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommendations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archetype_content', schema=None) as batch_op:
        batch_op.drop_column('recommendations')
        batch_op.drop_column('mission')
        batch_op.drop_column('health_tips')
        batch_op.drop_column('business_potential')
        batch_op.drop_column('financial_tip')
        batch_op.drop_column('partner_type')
        batch_op.drop_column('avoid_spheres')
        batch_op.drop_column('shadow_side')
        batch_op.drop_column('full_text')

    # ### end Alembic commands ###
